<?php

/**
 * @file
 * Fanciblock module creates configurable feature boxes with images or icons.
 *
 * Maintainer: Wilmoth Andy Shillingford
 * Inspired by Iconbox module by Himanshu Shakhar (developmenticon)
 */

/**
 *  Implementation of hook_config_info()
 */
function fanciblock_config_info() {
  $prefixes['fanciblock.settings'] = array(
    'label' => t('Fanciblock settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 *  Implementation of hook_cron()
 *  
 *  Deletes unused fanciblock settings. Fanciblocks are added via Layout builder
 *  and their settings are saved in hook_block_save to fanciblock.settings.json.
 *  
 *  When a block is removed from Layout builder, there is no way to tell this
 *  happened immediately. This may change; see https://github.com/backdrop/backdrop-issues/issues/767.
 *  
 *  Until then this checks for removed layout blocks to delete their settings on 
 *  cron run.
 *  
 */
/* function fanciblock_cron() {
  // Find all Fanciblocks stored in Layout settings and save to an array.
  $all_layouts = layout_get_all_configs('layout');
  $layouts = array();
  foreach($all_layouts as $layout_name => $active_layouts) {
    foreach($active_layouts['content'] as $uuid => $block) {
      if($block['data']['module'] == 'fanciblock') {
        $layouts[] = $block['data']['settings']['block_settings']['fanciblock_name'];
      }
    }
  }
  // Then check if the Fanciblocks in our Fanciblock config are actually in a 
  // layout by checking if its ID is in the $layouts array we just built.
  $settings = config('fanciblock.settings');
  $data = $settings->get();
  foreach($data as $key => $setting) {
    // If the Fanciblock setting is no longer in a Layout, delete it.
    if(is_null($setting) || (is_array($setting) && !in_array($key, $layouts))) {
      unset($data[$key]);
    }
  }
  $settings->setData($data);
  $settings->save();
}
 */

/**
 * Implements hook_permission().
 */
function fanciblock_permission() {
  $perms = array(
    'administer fanciblock' => array(
      'title' => t('Administer Icon Box'),
      'restrict access' => TRUE,
    ),
  );
  return $perms;
}

/**
 * Implements hook_library_info().
 */
function fanciblock_library_info() {
  // Library One.
  $libraries['fontawesome'] = array(
    'title' => 'Font Awesome',
    'website' => 'http://fortawesome.github.com/Font-Awesome/',
    'version' => '1.2',
    'css' => array(
      backdrop_get_path('module', 'fanciblock') . '/fontawesome/css/font-awesome.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_menu().
 */
function fanciblock_menu() {
  //List box.
  $items['admin/config/media/fanciblocks'] = array(
    'title' => 'List all Fanciblocks',
    'page callback' => 'fanciblock_overview_page',
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.admin.inc',
  );
  //List box.
  $items['admin/config/media/fanciblocks/%fanciblock'] = array(
    'title' => 'List Box',
    //'title callback' => 'fanciblock_title_callback',
    'title arguments' => array(4),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('fanciblock_box_overview_form', 4),
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.box.admin.inc',
  );
  //Add box.
  $items['admin/config/media/fanciblocks/%fanciblock/add-box'] = array(
    'title' => 'Add box',
    'page callback' => 'fanciblock_box_add_box',
    'page arguments' => array(4),
    'access arguments' => array('administer fanciblock'),
    'type' => MENU_CALLBACK,
    'file' => 'fanciblock.box.admin.inc',
  );
  //Edit box.
  $items['admin/config/media/fanciblocks/%fanciblock/%/edit'] = array(
    'title' => 'Edit box',
    //'title callback' => 'fanciblock_title_callback',
    'title arguments' => array(4),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('fanciblock_box_edit_box', 4, 5, 6),
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.box.admin.inc',
    'type' => MENU_CALLBACK,
  );
  //Delete box.
  $items['admin/config/media/fanciblocks/%fanciblock/%/delete'] = array(
    'title' => 'Delete box',
    //'title callback' => 'fanciblock_title_callback',
    'title arguments' => array(4),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('fanciblock_box_delete_box', 4, 5, 6),
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.box.admin.inc',
    'type' => MENU_CALLBACK,
  );
  // THis is just a fake link. It will show up in fanciblock contextual menus
  // so that we can identify them. THis is because all blocks have their 
  // $root_path set as 'admin/structure/menu/manage/%' because of Layout, and
  // that makes it hard to figure which block belongs to which module.
  $items['fanciblock/stub/%'] = array(
    'title' => 'Block information',
    'type' => MENU_CALLBACK,
    'context' => MENU_CONTEXT_INLINE,
    'page callback' => '/',
    'menu_name' => 'fanciblock',
    'access callback' => TRUE,
  );
  // To use local task menu items, there must be a parent page.
  $items['fanciblock'] = array(
    'title' => 'The stub page',
    'page callback' => 'node',
    'menu_name' => 'fanciblock',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Title callback.
 */
function fanciblock_title_callback($fanciblock) {
  return $fanciblock['settings']['fanciblock_title'];
}

/**
 * Loads a Fanciblock.
 */
function fanciblock_load($fanciblock_name) {
  if ($fanciblock_name == 'new-fanciblock') {
    return fanciblock_default_settings();
  }
  // $config = config('fanciblock.settings');
  // $fanciblock = $config->get($fanciblock_name);
  return fanciblock_get_settings($fanciblock_name);
}

/**
 *  Implements hook_menu_contextual_links_alter
 *  
 *  This adds links to edit individual fanciblock boxes tot the main fanciblock
 *  contextual links menu. It uses the stub contextual link menu item to find
 *  fanciblocks, then deletes the stub.
 */
function fanciblock_menu_contextual_links_alter(&$links, $router_item, $root_path) {
 if ($root_path == 'fanciblock/stub/%') {
    $fanciblock = $router_item['map'][2];
    $config = fanciblock_get_settings($fanciblock);
    if($config) {
      $config = $config['boxes'];
      foreach($config as $box) {
        $links['fb' . $box['boxid']] = array(
          'title' => 'Edit ' . $box['box_title'],
          'href' => 'admin/config/media/fanciblocks/' . $box['fanciblock_name'] . '/' . $box['boxid'] . '/edit',
          'localized_options' => array(),
        );
      }
      $links['ls' . $fanciblock] = array(
        'title' => 'Re-order',
        'href' => 'admin/config/media/fanciblocks/' . $fanciblock,
        'localized_options' => array(),
      );
    }
  unset($links['fanciblock-']);
  }
}

/**
 * Implements hook_theme().
 */
function fanciblock_theme() {
  return array(
    'fanciblock_admin_overview' => array(
      'file' => 'fanciblock.admin.inc',
      'variables' => array('title' => NULL, 'name' => NULL),
    ),
    'fanciblock_box_overview_form' => array(
      'file' => 'fanciblock.box.admin.inc',
      'render element' => 'form',
    ),
    'fanciblock_box_preview' => array(
      'file' => 'theme/fanciblock.theme.inc',
      'render element' => 'form',
    ),
    'fanciblock_fontawesome_icon_build' => array(
      'file' => 'fanciblock.box.admin.inc',
      'variables' => array('class' => NULL, 'size' => NULL, 'style' => NULL, 'looks' => NULL, 'color' => NULL),
    ),
    'fanciblock_horizontal' => array(
      'variables' => array('fanciblock_data' => NULL, 'settings' => NULL, 'preview' => FALSE),
      'template' => 'theme/fanciblock-horizontal',
      'preprocess functions' => array('template_preprocess_fanciblock_content'),
      'file' => 'theme/fanciblock.theme.inc',
    ),
    'fanciblock_vertical' => array(
      'variables' => array('fanciblock_data' => NULL, 'settings' => NULL, 'preview' => FALSE),
      'template' => 'theme/fanciblock-vertical',
      'preprocess functions' => array('template_preprocess_fanciblock_content'),
      'file' => 'theme/fanciblock.theme.inc',
    ),
  );
}


/**
 * Title callback for the fanciblock overview page.
 */
function fanciblock_overview_title($fanciblock) {
  return $fanciblock['title'];
}

function fanciblock_autoload_info() {
  return array(
    'Fanciicon' => 'block.fanciicon.inc',
    'Fanciblock' => 'block.fanciblock.inc',
  );
}

/**
 * Implements hook_block_info().
 */
function fanciblock_block_info() {
  $blocks = array();
  $blocks['fanciblock']['info'] = t('Fanciblock image');
  $blocks['fanciblock']['description'] = t('Fanciblock image');
  $blocks['fanciblock']['class'] = 'Fanciblock';
  
  $blocks['fanciicon']['info'] = t('Fanciblock icon');
  $blocks['fanciicon']['description'] = t('Fanciblock icon');
  $blocks['fanciicon']['class'] = 'Fanciicon';
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
/* function fanciblock_block_configure($delta = '', $settings = array()) {
  $form = array();
  if ($delta == 'fanciblock' || $delta == 'fanciicon') {
    module_load_include('inc', 'fanciblock', 'fanciblock.admin');
    $fanciblock = fanciblock_get_settings($settings['fanciblock_name']);
    if(!empty($fanciblock)) {
      $settings = $fanciblock;
    }
    $form = fanciblock_edit_box('edit', $delta, $settings);
  }
  return $form;
}
 */
/**
 *  Saves a block (fanciblock) during block configure.
 *  
 *  @param [in] $delta Parameter_Description
 *  @return Return_Description
 *  
 *  @details Details
 */
/* function fanciblock_block_save($delta, &$edit = array()) {
  $edit = _flatten_fanciblock_settings($edit);
  if ($delta == 'fanciblock' || $delta == 'fanciicon') {
    $config = config('fanciblock.settings');
    
    // Set up defaults.
    $default_fid = $config->get('default_fid');
    $default_fanciblock_uri = $config->get('default_fanciblock_uri');
    $default_box = array(
      'fanciblock_name' => $edit['fanciblock_name'], 
      'boxid' => '', 
      'box_title' => $edit['fanciblock_title'], 
      'weight' => 0, 
      'box_content' => array('value' => 'Hello!'),
      'icon_link' => '',
    );
    if ($delta == 'fanciblock') {
      $default_box += array(
        'fanciblock_fid' => $default_fid, 
        'fanciblock_uri' => $default_fanciblock_uri, 
      );
    }
    elseif($delta == 'fanciicon') {
      $default_box += array(
        'fontawesome_icon' => 'fa-tablet',
        'fontawesome_icon_color' => '#333333',
      );
    }
  }
}
 */
/**
 * Save a fanciblock box.
 *
 * @param $box
 *   An array representing a fanciblock box:
 *   - boxid: The unique id of the box
 *   - fanciblock_name: The parent fanciblock name.
 *   - box_title: The human readable box title.
 *   - weight: The box order value.
 *   - fontawesome_icon: The font awesome icon.
 *   - box_content: The box content.
 */
function fanciblock_box_save($settings) {
  config_set('fanciblock.settings', $settings['settings']['fanciblock_name'], $settings);
}

/**
 * Create a fanciblock box with default values.
 */
function _fanciblock_add_default_boxes($number, $fanciblock, $delta) {
  // Set up defaults.
  $config = config('fanciblock.settings');
  $default_fid = $config->get('default_fid');
  $default_fanciblock_uri = $config->get('default_fanciblock_uri');


  $boxes = array();
  $i = 1;
  while($i <= $number) {
    $id = uniqid();
    $default_box = array(
      'fanciblock_name' => isset($fanciblock['fanciblock_name']) ? $fanciblock['fanciblock_name'] : '', 
      'boxid' => '', 
      'box_title' => isset($fanciblock['fanciblock_title']) ? $fanciblock['fanciblock_title'] : 'Box title', 
      'weight' => 0, 
      'box_content' => array('value' => 'Hello!'),
      'icon_link' => '',
    );
    if ($delta == 'fanciblock') {
      $default_box += array(
        'fanciblock_fid' => $default_fid, 
        'fanciblock_uri' => $default_fanciblock_uri, 
      );
    }
    elseif($delta == 'fanciicon') {
      $default_box += array(
        'fontawesome_icon' => 'monitor',
        'fontawesome_icon_color' => '#333333',
      );
    }
    $title = $default_box['box_title'];
    $default_box['boxid'] = $i . $id;
    $default_box['box_title'] = empty($title) ? '' : $title . ' ' . $i;
    $default_box['fanciblock_type'] = (string) $delta;
    $boxes[$i . $id] = $default_box;
    $i++;
  }
  return $boxes;
}

/**
 * Implements hook_block_view().
 */
/* function fanciblock_block_view($delta = '', $settings = array(), $contexts = array()) {
  if ($delta == 'fanciblock' || $delta == 'fanciicon') {
    $fanciblock = fanciblock_get_settings($settings['fanciblock_name']);

    // Block settings stay in Layout even if the module is unintalled, and cause
    // white-screen on view. So dont show anything unless we find a config file.
    if($fanciblock) {
      $data['subject'] = NULL;
      // THis adds the a fake link in the fanciblock menu so that we can identify it.
      // See hook_menu for details.
      $data['content'] =  array(
        '#markup' => fanciblock_build_fanciblocks($delta, $fanciblock['settings']),
        '#contextual_links' => array(
          'fanciblock' => array('fanciblock/stub', array($settings['fanciblock_name'])),
        ),
      );
      return $data;
    }
  }
}
 */

/**
 * Build a fanciblock and all contained boxes and load necessary CSS and JS.
 *
 * @return
 *   Array of fanciblocks with contained boxes data.
 */
function fanciblock_build_fanciblocks($delta, $settings) {
  $boxes = $settings['boxes'];
  backdrop_sort($boxes, array('weight' => SORT_NUMERIC));
  
  backdrop_add_css(backdrop_get_path('module', 'fanciblock') . '/fontawesome/css/font-awesome.css'); // add library fontawesome.css
  backdrop_add_css(backdrop_get_path('module', 'fanciblock') . '/css/fanciblock.css'); // add css
  backdrop_add_js(backdrop_get_path('module', 'fanciblock') . '/js/fanciblock.js'); // add js
  
  $settings['delta'] = $delta;
  if($settings['icon_position'] == 'right' || $settings['icon_position'] == 'left') {
    return theme('fanciblock_horizontal', array('fanciblock_data' => $boxes, 'settings' => $settings, 'preview' => FALSE));
  }
  elseif($settings['icon_position'] == 'top' || $settings['icon_position'] == 'boxcut') {
    return theme('fanciblock_vertical', array('fanciblock_data' => $boxes, 'settings' => $settings, 'preview' => FALSE));
  }
}


/**
 * Flattens the settings array to remove parent keys.
 */
function _flatten_fanciblock_settings($settings = array()) {
  $results = &backdrop_static('fanciblock_flatten', array());
  foreach($settings as $key => $setting) {
    if(is_array($setting)) {
      _flatten_fanciblock_settings ($setting);
    }
    else {
      $results[$key] = $setting;
    }
  }
  return $results;
}

/**
 * Validate a form element that should have an integer value.
 */
function _fanciblock_validate_positive_integer($element, &$form_state) {
  $value = $element['#value'];
  if (!is_numeric($value) || intval($value) != $value || $value < 0) {
    form_error($element, t('%name must be a positive integer.', array('%name' => $element['#title'])));
  }
}

/**
 * Validate a form element that should have an valid color value.
 */
function _fanciblock_validate_color_value($element, &$form_state) {
  $value = $element['#value'];
  // Only accept hexadecimal CSS color strings.
  if (!preg_match('/^#([a-f0-9]{3}){1,2}$/iD', $value) && $value != 'transparent') {
    form_error($element, t('%name must be a valid hexadecimal CSS color value.', array('%name' => $element['#title'])));
  }
}

/**
 * Load all fanciblock data.
 *
 * @return
 *   Array of fanciblock data.
 */
function fanciblock_get_settings($fanciblock_name = NULL) {
  $item = tempstore_get('fanciblock', $fanciblock_name);
  dpm($item);
  if ($item) {
    return $item;
  }

  return NULL;
}

/**
 * Load all fanciblock data.
 *
 * @return
 *   Array of fanciblock data.
 */
function fanciblock_default_settings() {
  return array(
    'fanciblock_type' => '',
    'fanciblock_title' => '',
    'fanciblock_name' => '',
    'grid' => '3',
    'icon_position' => 'top',
    'icon_style' => 'none',
    'icon_size' => 'medium',
    'box_padding' => '20',
    'icon_bg_color_status' => 0,
    'icon_bg_color' => '#333333',
    'icon_border_status' => 0,
    'icon_border_width' => '1',
    'icon_border_style' => 'solid',
    'icon_border_color' => '#efefef',
    'box_bg_color_status' => 0,
    'box_bg_color' => '#efefef',
    'box_border_status' => 0,
    'box_border_width' => '1',
    'box_border_style' => 'solid',
    'box_border_color' => '#efefef',
  );
}

/**
 * Submit handler for layout_block_configure_form() to add a condition.
 */
function fanciblock_box_edit_box_open($form, &$form_state) {
  $fanciblock = $form_state['fanciblock'];
  dpm($fanciblock);
  // $fanciblock['boxes'] = $form_state['values']['block_settings']['boxes'];
  $fanciblock['layout_name'] = $form_state['layout']->name;
  $fanciblock['block'] = $form_state['block']->uuid;
    // $link = 'admin/config/media/fanciblocks/new-fanciblock/' . $key . '/edit';
  $button = $form_state['clicked_button']['#name'];
  fanciblock_set_tempstore($fanciblock);
  $form_state['redirect'] = 'admin/config/media/fanciblocks/' . $fanciblock['fanciblock_name'] . '/' . $button . '/edit';
}


/**
 * Process fanciblock box add/edit form submissions.
 */
function fanciblock_box_edit_box_cancel_submit($form, &$form_state) {
  $fanciblock = $form_state['values']['fanciblock'];
  dpm($fanciblock, 'fanciblock_box_edit_box_cancel_submit');
  $layout_name = $fanciblock['layout_name'];
  // $form_state['redirect'] = 'admin/config/media/fanciblocks/' . $box['fanciblock_name'];
  $form_state['redirect'] = 'admin/structure/layouts/manage/' . $layout_name . '/configure-block/editor/' . $fanciblock['block'];
}

/**
 * Process fanciblock box add/edit form submissions.
 */
function fanciblock_box_edit_box_submit($form, &$form_state) {
  // The entire fancibox
  $fanciblock = $form_state['values']['fanciblock'];
  global $user;
  
  // Save common form values
  $box = array(
    'fanciblock_name' => $fanciblock['fanciblock_name'],
    'box_title' => $form_state['values']['box_title'],
    'weight' => $form_state['values']['weight'],
    'box_content' => $form_state['values']['box_content'],
    'icon_link' => $form_state['values']['icon_link'],
    'boxid' => $form_state['values']['boxid'] ? $form_state['values']['boxid'] : uniqid(),
    'fanciblock_type' => $fanciblock['fanciblock_type'],
  );
  // Save type-specific values. Start with fanciblock.
  if($form_state['values']['fanciblock_type'] == 'fanciblock') {
    // If the image field is set, save the image.
    if($form_state['values']['fanciblock_uri']) {
      $file = file_load($form_state['values']['fanciblock_uri']);
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);
      file_usage_add($file, 'user', 'user', $user->uid);
      $box['fanciblock_fid'] = $file->fid;
      $box['fanciblock_uri'] = $file->uri;
    }
    // Otherwise keep the previous values. (We avoid empty boxes.)
    else {
      $box['fanciblock_fid'] = $fanciblock['boxes'][$form_state['values']['boxid']]['fanciblock_fid'];
      $box['fanciblock_uri'] = $fanciblock['boxes'][$form_state['values']['boxid']]['fanciblock_uri'];
    }
  }
  // If its a fanciicon, save the icon value. Its a select so its never empty.
  elseif($form_state['values']['fanciblock_type'] == 'fanciicon') {
    $box['fontawesome_icon'] = $form_state['values']['fontawesome_icon'];
    $box['fontawesome_icon_color'] = $form_state['values']['fontawesome_icon_color'];
  }
  $fanciblock['boxes'][$box['boxid']] = $box;
  dpm($fanciblock);
  fanciblock_set_tempstore($fanciblock);
  $layout_name = $fanciblock['layout_name'];
  // $form_state['redirect'] = 'admin/config/media/fanciblocks/' . $box['fanciblock_name'];
  $form_state['redirect'] = 'admin/structure/layouts/manage/' . $layout_name . '/configure-block/editor/' . $fanciblock['block'];
  backdrop_set_message(t('Your configuration has been saved.'));
}

/**
 * AJAX callback to update the underlying layout form after updating a block.
 */
function fanciblock_ajax_update($form, $form_state) {

  // Display error messages in the form if any.
  if (form_get_errors()) {
    $html = '';
    $html .= theme('status_messages');
    $html .= backdrop_render($form);
    $title = isset($form['#title']) ? $form['#title'] : backdrop_get_title();
    $commands[] = ajax_command_open_modal_dialog($title, $html, array('dialogClass' => 'layout-dialog'));
  }
  else {
    // Get the dialog path as set in the redirect.
    $dialog_path = $form_state['redirect'];
    $page_callback_result = NULL;
    if ($router_item = menu_get_item($dialog_path)) {
      if ($router_item['access']) {
        if ($router_item['include_file']) {
          require_once BACKDROP_ROOT . '/' . $router_item['include_file'];
        }
        $page_callback_result = call_user_func_array($router_item['page_callback'], $router_item['page_arguments']);
      }
    }
    $html = is_string($page_callback_result) ? $page_callback_result : backdrop_render($page_callback_result);
    if (isset($page_callback_result['#title'])) {
      $title = $page_callback_result['#title'];
    }
    else {
      $title = $router_item['title'];
    }
    $commands[] = ajax_command_open_modal_dialog($title, $html, array('dialogClass' => 'layout-dialog'));
  }

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Process fanciblock box add/edit form submissions.
 */
function fanciblock_delete_box($form, &$form_state) {
  $button = $form_state['clicked_button']['#name'];
  unset($form_state['boxes'][$button]);
  $form_state['rebuild'] = TRUE;
}


/**
 * Submit handler for layout_settings_form() that adds an additional path.
 */
function fanciblock_add_additional_box($form, &$form_state) {
  $new_box = _fanciblock_add_default_boxes(1, array('fanciblock_name' => $form_state['fanciblock_name'], 'fanciblock_title' => $form_state['fanciblock_title']), $form_state['delta']);
  $form_state['boxes'] += $new_box;
  $form_state['rebuild'] = TRUE;
}

/**
 * AJAX handler for layout_settings_form().
 *
 * Returns updated contexts and additional path form data when adding or
 * removing additional paths.
 */
function fanciblock_box_add_delete_ajax($form, &$form_state) {
  // $commands[] = ajax_command_remove('.l-messages');
  // $commands[] = ajax_command_html('#layout-messages', theme('status_messages'));
  $commands[] = ajax_command_html('#fanciblock-box-wrapper', backdrop_render($form['box_edit']));
  // $commands[] = ajax_command_html('#layout-contexts', backdrop_render($form['context_wrapper']));
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Store changes to a layout or menu item in the temporary store.
 *
 * @param Layout|LayoutMenuItem $item
 *   The Layout item to save into tempstore.
 * @param string $type
 *   The type of item to save. Must be either "layout" or "menu_item".
 */
function fanciblock_set_tempstore($fanciblock) {
  if (empty($fanciblock['fanciblock_name'])) {
    return;
  }

  tempstore_set('fanciblock', $fanciblock['fanciblock_name'], $fanciblock, 604800);
}
