<?php

/**
 * @file
 * Fanciblock module creates configurable feature boxes with images or icons.
 *
 * Maintainer: Wilmoth Andy Shillingford
 * Inspired by Iconbox module by Himanshu Shakhar (developmenticon)
 */

/**
 *  Implementation of hook_config_info()
 */
function fanciblock_config_info() {
  $prefixes['fanciblock.settings'] = array(
    'label' => t('Fanciblock settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 *  Implementation of hook_cron()
 *  
 *  Deletes unused fanciblock settings. Fanciblocks are added via Layout builder
 *  and their settings are saved in hook_block_save to fanciblock.settings.json.
 *  
 *  When a block is removed from Layout builder, there is no way to tell this
 *  happened immediately. This may change; see https://github.com/backdrop/backdrop-issues/issues/767.
 *  
 *  Until then this checks for removed layout blocks to delete their settings on 
 *  cron run.
 *  
 */
function fanciblock_cron() {
  // Find all Fanciblocks stored in Layout settings and save to an array.
  $all_layouts = layout_get_all_configs('layout');
  $layouts = array();
  foreach($all_layouts as $layout_name => $active_layouts) {
    foreach($active_layouts['content'] as $uuid => $block) {
      if($block['data']['module'] == 'fanciblock') {
        $layouts[] = $block['data']['settings']['block_settings']['fanciblock_name'];
      }
    }
  }
  // Then check if the Fanciblocks in our Fanciblock config are actually in a 
  // layout by checking if its ID is in the $layouts array we just built.
  $settings = config('fanciblock.settings');
  $data = $settings->get();
  foreach($data as $key => $setting) {
    // If the Fanciblock setting is no longer in a Layout, delete it.
    if(is_null($setting) || (is_array($setting) && !in_array($key, $layouts))) {
      unset($data[$key]);
    }
  }
  $settings->setData($data);
  $settings->save();
}


/**
 * Implements hook_permission().
 */
function fanciblock_permission() {
  $perms = array(
    'administer fanciblock' => array(
      'title' => t('Administer Icon Box'),
      'restrict access' => TRUE,
    ),
  );
  return $perms;
}

/**
 * Implements hook_library_info().
 */
function fanciblock_library_info() {
  // Library One.
  $libraries['fontawesome'] = array(
    'title' => 'Font Awesome',
    'website' => 'http://fortawesome.github.com/Font-Awesome/',
    'version' => '1.2',
    'css' => array(
      backdrop_get_path('module', 'fanciblock') . '/fontawesome/css/font-awesome.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_menu().
 */
function fanciblock_menu() {
  //List box.
  $items['admin/config/media/fanciblocks'] = array(
    'title' => 'List all Fanciblocks',
    'page callback' => 'fanciblock_overview_page',
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.admin.inc',
  );
  //List box.
  $items['admin/config/media/fanciblocks/%fanciblock'] = array(
    'title' => 'List Box',
    'title callback' => 'fanciblock_title_callback',
    'title arguments' => array(4),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('fanciblock_box_overview_form', 4),
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.box.admin.inc',
  );
  //Edit box.
  $items['admin/config/media/fanciblocks/%fanciblock/%/edit'] = array(
    'title' => 'Edit box',
    'title callback' => 'fanciblock_title_callback',
    'title arguments' => array(4),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('fanciblock_box_edit_box', 4, 5, 6),
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.box.admin.inc',
  );
  //Delete box.
  $items['admin/config/media/fanciblocks/%fanciblock/%/delete'] = array(
    'title' => 'Delete box',
    'title callback' => 'fanciblock_title_callback',
    'title arguments' => array(4),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('fanciblock_box_delete_box', 4, 5, 6),
    'access arguments' => array('administer fanciblock'),
    'file' => 'fanciblock.box.admin.inc',
  );
  // THis is just a fake link. It will show up in fanciblock contextual menus
  // so that we can identify them. THis is because all blocks have their 
  // $root_path set as 'admin/structure/menu/manage/%' because of Layout, and
  // that makes it hard to figure which block belongs to which module.
  $items['fanciblock/stub/%'] = array(
    'title' => 'Block information',
    'type' => MENU_CALLBACK,
    'context' => MENU_CONTEXT_INLINE,
    'page callback' => '/',
    'menu_name' => 'fanciblock',
    'access callback' => TRUE,
  );
  // To use local task menu items, there must be a parent page.
  $items['fanciblock'] = array(
    'title' => 'The stub page',
    'page callback' => 'node',
    'menu_name' => 'fanciblock',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Title callback.
 */
function fanciblock_title_callback($fanciblock) {
  return $fanciblock['settings']['fanciblock_title'];
}

/**
 * Loads a Fanciblock.
 */
function fanciblock_load($fanciblock_name) {
  $config = config('fanciblock.settings');
  $fanciblock = $config->get($fanciblock_name);
  return $fanciblock;
}

/**
 *  Implements hook_menu_contextual_links_alter
 *  
 *  This adds links to edit individual fanciblock boxes tot the main fanciblock
 *  contextual links menu. It uses the stub contextual link menu item to find
 *  fanciblocks, then deletes the stub.
 */
function fanciblock_menu_contextual_links_alter(&$links, $router_item, $root_path) {
 if ($root_path == 'fanciblock/stub/%') {
    $fanciblock = $router_item['map'][2];
    $config = fanciblock_get_settings($fanciblock);
    if($config) {
      $config = $config['boxes'];
      foreach($config as $box) {
        $links['fb' . $box['boxid']] = array(
          'title' => 'Edit ' . $box['box_title'],
          'href' => 'admin/config/media/fanciblocks/' . $box['fanciblock_name'] . '/' . $box['boxid'] . '/edit',
          'localized_options' => array(),
        );
      }
      $links['ls' . $fanciblock] = array(
        'title' => 'Re-order',
        'href' => 'admin/config/media/fanciblocks/' . $fanciblock,
        'localized_options' => array(),
      );
    }
  unset($links['fanciblock-']);
  }
}

/**
 * Implements hook_theme().
 */
function fanciblock_theme() {
  return array(
    'fanciblock_admin_overview' => array(
      'file' => 'fanciblock.admin.inc',
      'variables' => array('title' => NULL, 'name' => NULL),
    ),
    'fanciblock_box_overview_form' => array(
      'file' => 'fanciblock.box.admin.inc',
      'render element' => 'form',
    ),
    'fanciblock_fontawesome_icon_build' => array(
      'file' => 'fanciblock.box.admin.inc',
      'variables' => array('class' => NULL, 'size' => NULL, 'style' => NULL, 'looks' => NULL, 'color' => NULL),
    ),
    'fanciblock_horizontal' => array(
      'variables' => array('fanciblock_data' => NULL, 'settings' => NULL, 'preview' => FALSE),
      'template' => 'theme/fanciblock-horizontal',
      'preprocess functions' => array('template_preprocess_fanciblock_content'),
      'file' => 'theme/fanciblock.theme.inc',
    ),
    'fanciblock_vertical' => array(
      'variables' => array('fanciblock_data' => NULL, 'settings' => NULL, 'preview' => FALSE),
      'template' => 'theme/fanciblock-vertical',
      'preprocess functions' => array('template_preprocess_fanciblock_content'),
      'file' => 'theme/fanciblock.theme.inc',
    ),
  );
}


/**
 * Title callback for the fanciblock overview page.
 */
function fanciblock_overview_title($fanciblock) {
  return $fanciblock['title'];
}

/**
 * Implements hook_block_info().
 */
function fanciblock_block_info() {
  $blocks = array();
  $blocks['fanciblock']['info'] = t('Fanciblock image');
  $blocks['fanciblock']['description'] = t('Fanciblock image');
  
  $blocks['fanciicon']['info'] = t('Fanciblock icon');
  $blocks['fanciicon']['description'] = t('Fanciblock icon');
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function fanciblock_block_configure($delta = '', $settings = array()) {
  $form = array();
  if ($delta == 'fanciblock' || $delta == 'fanciicon') {
    module_load_include('inc', 'fanciblock', 'fanciblock.admin');
    if(!empty($settings)) {
      $fanciblock = fanciblock_get_settings($settings['fanciblock_name']);
      $settings = _flatten_fanciblock_settings ($fanciblock['settings']);
    }
    $form = fanciblock_edit_box('edit', $delta, $settings);
  }
  return $form;
}

/**
 *  Saves a block (fanciblock) during block configure.
 *  
 *  @param [in] $delta Parameter_Description
 *  @return Return_Description
 *  
 *  @details Details
 */
function fanciblock_block_save($delta, &$edit = array()) {
  if ($delta == 'fanciblock' || $delta == 'fanciicon') {
    $config = config('fanciblock.settings');
    
    // Set up defaults.
    $default_fid = $config->get('default_fid');
    $default_fanciblock_uri = $config->get('default_fanciblock_uri');
    $default_box = array(
      'fanciblock_name' => $edit['fanciblock_name'], 
      'boxid' => '', 
      'box_title' => $edit['fanciblock_title'], 
      'weight' => 0, 
      'box_content' => array('value' => 'Hello!'),
      'icon_link' => '',
    );
    if ($delta == 'fanciblock') {
      $default_box += array(
        'fanciblock_fid' => $default_fid, 
        'fanciblock_uri' => $default_fanciblock_uri, 
      );
    }
    elseif($delta == 'fanciicon') {
      $default_box += array(
        'fontawesome_icon' => 'fa-tablet',
        'fontawesome_icon_color' => '#333333',
      );
    }
    
    // Check and see if this block's settings already exist. Theyre saved in
    // config, keyed by the block's unique name (fanciblock_name).
    $settings = $config->get($edit['fanciblock_name']);
    // If we dont find the settings, this is a new block being built, so
    // build and save a default box for each grid.
    if(!$settings) {
      $boxes = _fanciblock_add_default_boxes($edit['grid']['grid'], $default_box, $delta);
      $settings['boxes'] = $boxes;
      //fanciblock_box_save($edit, $boxes);
    }
    // If we are adding boxes, Grid number will be more than the number of 
    // settings.
    elseif($edit['grid']['grid'] > count($settings['boxes'])) {
      $adding = $edit['grid']['grid'] - count($settings);
      $boxes = _fanciblock_add_default_boxes($adding, $default_box, $delta);
      $settings['boxes'] += $boxes;
      
      //fanciblock_box_save($edit, $settings);
    }
    // Theres no safe way to decrease the number of boxes, so we dont allow that.
    elseif($edit['grid']['grid'] < count($settings)) {
      form_set_error('', 'Cannot decrease number of boxes, please delete box instead');
    }
    $settings['settings'] = $edit;
    fanciblock_box_save($settings);
  }
}

/**
 * Save a fanciblock box.
 *
 * @param $box
 *   An array representing a fanciblock box:
 *   - boxid: The unique id of the box
 *   - fanciblock_name: The parent fanciblock name.
 *   - box_title: The human readable box title.
 *   - weight: The box order value.
 *   - fontawesome_icon: The font awesome icon.
 *   - box_content: The box content.
 */
function fanciblock_box_save($settings) {
  config_set('fanciblock.settings', $settings['settings']['fanciblock_name'], $settings);
}

/**
 * Create a fanciblock box with default values.
 */
function _fanciblock_add_default_boxes($number, $default_box, $delta) {  
  $boxes = array();
  $title = $default_box['box_title'];
  $i = 1;
  while($i <= $number) {
    $id = uniqid();
    // Set the box title.
    $default_box['boxid'] = $i . $id;
    $default_box['box_title'] = $title . ' ' . $i;
    $default_box['fanciblock_type'] = (string) $delta;
    $boxes[$i . $id] = $default_box;
    $i++;
  }
  return $boxes;
}

/**
 * Implements hook_block_view().
 */
function fanciblock_block_view($delta = '', $settings = array(), $contexts = array()) {
  if ($delta == 'fanciblock' || $delta == 'fanciicon') {
    $fanciblock = fanciblock_get_settings($settings['fanciblock_name']);

    // Block settings stay in Layout even if the module is unintalled, and cause
    // white-screen on view. So dont show anything unless we find a config file.
    if($fanciblock) {
      $data['subject'] = NULL;
      // THis adds the a fake link in the fanciblock menu so that we can identify it.
      // See hook_menu for details.
      $data['content'] =  array(
        '#markup' => fanciblock_build_fanciblocks($delta, $fanciblock['settings']),
        '#contextual_links' => array(
          'fanciblock' => array('fanciblock/stub', array($settings['fanciblock_name'])),
        ),
      );
      return $data;
    }
  }
}


/**
 * Build a fanciblock and all contained boxes and load necessary CSS and JS.
 *
 * @return
 *   Array of fanciblocks with contained boxes data.
 */
function fanciblock_build_fanciblocks($delta, $settings) {
  // Load the config file.
  $fanciblock = fanciblock_get_settings($settings['fanciblock_name']);
  $boxes = $fanciblock['boxes'];
  backdrop_sort($boxes, array('weight' => SORT_NUMERIC));
  
  backdrop_add_css(backdrop_get_path('module', 'fanciblock') . '/fontawesome/css/font-awesome.css'); // add library fontawesome.css
  backdrop_add_css(backdrop_get_path('module', 'fanciblock') . '/css/fanciblock.css'); // add css
  backdrop_add_js(backdrop_get_path('module', 'fanciblock') . '/js/fanciblock.js'); // add js
  
  $settings = _flatten_fanciblock_settings($settings);
  $settings['delta'] = $delta;
  if($settings['icon-position'] == 'right' || $settings['icon-position'] == 'left') {
    return theme('fanciblock_horizontal', array('fanciblock_data' => $boxes, 'settings' => $settings, 'preview' => FALSE));
  }
  elseif($settings['icon-position'] == 'top' || $settings['icon-position'] == 'boxcut') {
    return theme('fanciblock_vertical', array('fanciblock_data' => $boxes, 'settings' => $settings, 'preview' => FALSE));
  }
}


/**
 * Flattens the settings array to remove parent keys.
 */
function _flatten_fanciblock_settings ($settings = array()) {
  $results = &backdrop_static('fanciblock_flatten', array());
  foreach($settings as $key => $setting) {
    if(is_array($setting)) {
      _flatten_fanciblock_settings ($setting);
    }
    else {
      $results[$key] = $setting;
    }
  }
  return $results;
}

/**
 * Validate a form element that should have an integer value.
 */
function _fanciblock_validate_positive_integer($element, &$form_state) {
  $value = $element['#value'];
  if (!is_numeric($value) || intval($value) != $value || $value < 0) {
    form_error($element, t('%name must be a positive integer.', array('%name' => $element['#title'])));
  }
}

/**
 * Validate a form element that should have an valid color value.
 */
function _fanciblock_validate_color_value($element, &$form_state) {
  $value = $element['#value'];
  // Only accept hexadecimal CSS color strings.
  if (!preg_match('/^#([a-f0-9]{3}){1,2}$/iD', $value) && $value != 'transparent') {
    form_error($element, t('%name must be a valid hexadecimal CSS color value.', array('%name' => $element['#title'])));
  }
}

/**
 * Load all fanciblock data.
 *
 * @return
 *   Array of fanciblock data.
 */
function fanciblock_get_settings($fanciblock_name) {
  return config_get('fanciblock.settings', $fanciblock_name);
}

